kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: kyverno-values-yaml
    files:
      - values.yaml

resources:
  - kyverno.yaml

namespace: kyverno
