kind: Kustomization
resources:
  - metallb.yaml
namespace: metallb-system

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: metallb-values-yaml
    files:
      - values.yaml
