description: kube-state-metrics deployment exposing cluster objects as metrics.
homepage: https://kubernetes.io/docs/tasks/debug/debug-cluster/resource-metrics-pipeline/
repository: https://github.com/kubernetes/kube-state-metrics
