apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics
  namespace: haproxy
spec:
  rules:
  - host: metrics.haproxy.k8s.teratan.lan
    http:
      paths:
      - backend:
          service:
            name: haproxy-haproxy-ingress-metrics
            port:
              number: 9101
        path: /
        pathType: Prefix
