# https://raw.githubusercontent.com/haproxy-ingress/charts/release-0.14/haproxy-ingress/values.yaml
#
# WARNING: Need to set --watch-ingress-without-class=true in deployment (can't do it from the helm chart)

controller:
  hostNetwork: true

  ingressClassResource:
    enabled: true
    default: true


  stats:
    enabled: true


  metrics:
    enabled: true
