description: NFS server manifests for shared persistent storage.
homepage: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
repository: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
