---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs
spec:
  interval: 5m
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs
      interval: 1m
  values:
    nfs:
      server: 192.168.66.8
      path: /speedy/K8sVolumes/
    storageClass:
      pathPattern: "${.PVC.namespace}-${.PVC.name}"
      defaultClass: true
