kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - serving-crds.yaml
---
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - serving-core.yaml
  - knative-istio.yaml
  - istio.yaml
  - net-istio.yaml
