kind: Kustomization

namespace: cert-manager

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cert-manager-values-yaml
    files:
      - values.yaml

resources:
  - cert-manager.yaml
  #  - issuer.yaml
  #  - policy.yaml
