description: Custom metrics aggregation resources for the homelab.
homepage: https://kubernetes.io/docs/tasks/debug/debug-cluster/resource-metrics-pipeline/
repository: https://github.com/kubernetes-sigs/metrics-server
